version: "3.8"

services:
  #service:
  #  build: .
  #  ports:
  #    - "4000:4000"
  database:
    image: postgres
    restart: always
    volumes:
      - employees_service_volume:/var/postgres/employees_service_volume
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USERNAME: postgres
    ports:
      - "127.0.0.1:5432:5432"

volumes:
  employees_service_volume:
